[plugins]

androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "plugin-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[versions]

agp = "8.13.1"
kotlin = "2.2.21"
plugin-compose = "1.9.3"

kotlinx-immutable-list = "0.4.0"

coroutines = "1.10.2"

haze = "1.6.10"
hypnoticcanvas = "0.4.1"

android-compose-activity = "1.11.0"
android-appcompat = "1.7.1"
android-core-ktx = "1.17.0"

[libraries]

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
android-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android-core-ktx" }
android-ui-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }
android-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "android-compose-activity" }
kotlinx-immutable-list = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable-list" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
shared-core-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
hypnoticcanvas = { module = "com.mikepenz.hypnoticcanvas:hypnoticcanvas", version.ref = "hypnoticcanvas" }
